---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
    - nginx

#    - db2

#- name: Begin mysql installation
#  hosts: all
#  become: yes
#  roles:
#     - { role: ansible-role-mysql, mysql_root_password: 'rootpass' }
